admin/__init__.py
"""
Admin blueprint
"""

from flask import Blueprint
from admin import views

admin_page = Blueprint('admin', __name__, url_prefix='/admin',
                       template_folder='templates')
define = views.define

admin/views.py
"""
Admin views
"""

from flask import abort
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for

from auth import login_required


def define(admin_page, models):
    """
    View functions and routes for the Admin pages
    """

    @admin_page.route('/')
    @login_required
    def admin():
        """
        Main admin landing page
        """
        owners = models.get_all_owners()
        n = 5
        owners = [owners[i:i + n] for i in range(0, len(owners), n)]
        return render_template('admin.html', owners=owners)

    @admin_page.route('/owner/<int:id>')
    @login_required
    def owner(id):
        """
        Owner details page
        """
        owner = models.get_owner(id)
        if not owner:
            return abort(404)
        owner.cars.sort(key=lambda c: (c.year, c.make, c.model))
        return render_template('owner.html', owner=owner)

    @admin_page.route('/add_owner', methods=('GET', 'POST'))
    @login_required
    def add_owner():
        """
        Add new owner page
        """
        if request.method == 'POST':
            owner_name = request.form['name']
            error = None

            if models.get_owner_by_name(owner_name):
                error = 'Owner exists'

            if error is None:
                owner = models.Owner()
                owner.name = owner_name
                models.add_owner(owner)
                return redirect(url_for('admin.owner', id=owner.id))

            flash(error)

        return render_template('add_owner.html')

    @admin_page.route('/owner/<int:id>/append_car', methods=('GET', 'POST'))
    @login_required
    def append_car(id):
        """
        Append new car to given owner
        """
        if request.method == 'POST':
            owner = models.get_owner(id)
            error = None

            if not owner:
                error = 'Owner exists'

            if error is None:
                make = request.form['make']
                model = request.form['model']
                year = request.form['year']
                car = models.Car(make=make, model=model, year=year)
                owner.cars.append(car)
                models.commit()
                return redirect(url_for('admin.owner', id=owner.id))

            flash(error)

        owner = models.get_owner(id)
        if not owner:
            return abort(404)
        return render_template('append_car.html', owner=owner)

    @admin_page.route('/edit_owner/<int:id>', methods=('GET', 'POST'))
    @login_required
    def edit_owner(id):
        """
        Change given owner information
        """
        if request.method == 'POST':
            new_name = request.form['name']
            error = None

            owner = models.get_owner(id)
            existing_owner_with_name = models.get_owner_by_name(new_name)
            if existing_owner_with_name:
                error = 'Owner exists with the given name'

            if error is None:
                owner.name = new_name
                models.commit()
                return redirect(url_for('admin.owner', id=owner.id))

            flash(error)

        owner = models.get_owner(id)
        if not owner:
            return abort(404)
        return render_template('edit_owner.html', owner=owner)

    @admin_page.route('/edit_car/<int:id>', methods=('GET', 'POST'))
    @login_required
    def edit_car(id):
        """
        Change given car information
        """
        if request.method == 'POST':
            error = None
            car = models.get_car(id)
            if not car:
                error = 'Car not found'

            if error is None:
                car.make = request.form['make']
                car.model = request.form['model']
                car.year = request.form['year']
                models.commit()
                return redirect(url_for('admin.owner', id=car.owner_id))

            flash(error)

        car = models.get_car(id)
        if not car:
            return abort(404)
        owner = car.owner
        return render_template('edit_car.html', owner=owner, car=car)

    @admin_page.route('/delete_owner/<int:id>', methods=('GET',))
    @login_required
    def delete_owner(id):
        """
        Delete owner
        """
        owner = models.get_owner(id)
        if owner:
            models.delete_owner(owner)
            return redirect(url_for('admin.admin'))
        return abort(404)

    @admin_page.route('/delete_car/<int:id>', methods=('GET',))
    @login_required
    def delete_car(id):
        """
        Delete given car
        """
        car = models.get_car(id)
        owner = models.get_owner(car.owner_id)
        if car:
            models.delete_car(car)
            return redirect(url_for('admin.owner', id=owner.id))
        return abort(404)

admin/templates/add_owner.html
{% extends "base.html" %}

{% block title %}Add owner{% endblock %}



{% block content %}
  <p>
    {% for message in get_flashed_messages() %}
      <div class="alert alert-info" role="info">{{ message }}</div>
    {% endfor %}
    <h2>Add owner</h2>
  </p>
  <form method="post" id="add_owner" action="">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="admin">
    </div>
    <p>
      <button type="submit" class="btn btn-primary">Add</button>
      <a href="{{ url_for('admin.admin') }}" class="btn btn-light">Cancel</a>
    </p>
  </form>
{% endblock %}

admin/templates/admin.html
{% extends "base.html" %}

{% block title %}Lexwheels Admin page{% endblock %}

{% block navbar %}
  {% if g.user %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('admin.admin') }}">Admin<span class="sr-only">(current)</span></a>
          </li>
  {% endif %}
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('owners') }}">Owners</a>
  </li>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-auto ">
        <h1 class="display-2"><span class="badge bg-light">Lexwheels <span class="badge badge-primary">Admin</span></span></h1>
      </div>
    </div>
    <div class="row justify-content-md-center">
      <div class="col-md-auto">
        <p class="lead">A place to transform owners and their cars.</p>
      </div>
    </div>
    <div class="row justify-content-md-center">
      <div class="col-md-12">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Owners</th>
              <th scope="col"></th>
              <th scope="col"></th>
              <th scope="col"></th>
              <th scope="col">
                <a class="btn btn-light" href="{{ url_for('admin.add_owner') }}">
                  Add Owner
                </a>
              </th>
            </tr>
          </thead>
          <tbody>
            {% for owner_chunk in owners %}
              <tr>
                {% for owner in owner_chunk %}
                  <td scope="row">
                    <a href="{{ url_for('admin.owner', id = owner.id) }}">{{ owner.name }}</a> 
                  </td>
                {% endfor %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

admin/templates/append_car.html
{% extends "base.html" %}

{% block title %}Register new car to {{ owner.name }}{% endblock %}


{% block content %}
  <p>
    {% for message in get_flashed_messages() %}
      <div class="alert alert-info" role="info">{{ message }}</div>
    {% endfor %}
    <h2>Register new car to {{ owner.name }}</h2>
  </p>
  <form method="post" id="edit_car" action="">
    <div class="form-group">
      <label for="make">Make</label>
      <input type="text" class="form-control" id="make" name="make">
    </div>
    <div class="form-group">
      <label for="model">Model</label>
      <input type="text" class="form-control" id="model" name="model">
    </div>
    <div class="form-group">
      <label for="year">Year</label>
      <input type="text" class="form-control" id="year" name="year">
    </div>
    <p>
      <button type="submit" class="btn btn-primary">Register</button>
      <a href="{{ url_for('admin.owner', id=owner.id) }}" class="btn btn-light">Cancel</a>
    </p>
  </form>
{% endblock %}

admin/templates/edit_car.html
{% extends "base.html" %}

{% block title %}Edit car owned by {{ owner.name }}{% endblock %}


{% block content %}
  <p>
    {% for message in get_flashed_messages() %}
      <div class="alert alert-info" role="info">{{ message }}</div>
    {% endfor %}
    <h2>Edit car owned by {{ owner.name }}</h2>
  </p>
  <form method="post" id="edit_car" action="">
    <div class="form-group">
      <label for="make">Make</label>
      <input type="text" class="form-control" id="make" name="make" placeholder="make" value="{{ car.make }}">
    </div>
    <div class="form-group">
      <label for="model">Model</label>
      <input type="text" class="form-control" id="model" name="model" placeholder="model" value="{{ car.model }}">
    </div>
    <div class="form-group">
      <label for="year">Year</label>
      <input type="text" class="form-control" id="year" name="year" placeholder="year" value="{{ car.year }}">
    </div>
    <p>
      <button type="submit" class="btn btn-primary">Update</button>
      <a href="{{ url_for('admin.owner', id=owner.id) }}" class="btn btn-light">Cancel</a>
    </p>
  </form>
{% endblock %}

admin/templates/edit_owner.html
{% extends "base.html" %}

{% block title %}Edit owner{% endblock %}


{% block content %}
  <p>
    {% for message in get_flashed_messages() %}
      <div class="alert alert-info" role="info">{{ message }}</div>
    {% endfor %}
    <h2>Edit {{ owner.name }}</h2>
  </p>
  <form method="post" id="edit_owner" action="">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="name" value="{{ owner.name }}">
    </div>
    <p>
      <button type="submit" class="btn btn-primary">Update</button>
      <a href="{{ url_for('admin.owner', id=owner.id) }}" class="btn btn-light">Cancel</a>
    </p>
  </form>
{% endblock %}

admin/templates/owner.html
{% extends "base.html" %}

{% block title %}Owner details {{ owner.name }}{% endblock %}

{% block navbar %}
  {% if g.user %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
    </li>
<li class="nav-item active">
  <a class="nav-link" href="{{ url_for('admin.admin') }}">Admin</a>
</li>
{% endif %}
<li class="nav-item">
  <a class="nav-link" href="{{ url_for('owners') }}">Owners</a>
</li>
{% endblock %}

{% block content %}
  <p>
    <div class="container">
      <div class="row justify-content-md-left">
        <div class="col-md-auto ">
          <h2>{{ owner.name }}</h2>
        </div>
        {% if g.user %}
        <div class="col-md-auto ">
          <div class="btn-group" role="group" aria-label="Basic example">
            <a href="{{ url_for('admin.edit_owner', id=owner.id) }}" class="btn btn-light">Edit</a>
            <a href="{{ url_for('admin.append_car', id=owner.id) }}" class="btn btn-light">Register new car</a>
            <a href="{{ url_for('admin.delete_owner', id=owner.id) }}" class="btn btn-light">Delete</a>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Year</th>
          <th scope="col">Make</th> 
          <th scope="col">Model</th>
          {% if g.user %}
            <th scope="col"></th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for car in owner.cars %}
          <tr>
            <th scope="row">{{car.year}}</th>
            <td>{{ car.make }}</td>
            <td>{{ car.model }}</td>
            {% if g.user %}
              <td>
                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                  <a href="{{ url_for('admin.edit_car', id=car.id) }}" class="btn btn-light">Edit</a>
                  <a href="{{ url_for('admin.delete_car', id=car.id) }}" class="btn btn-light">Delete</a>
                </div>
              </td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>      
  </p>
{% endblock %}